steps:
    # Build the Container
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/http-response-emulator:$COMMIT_SHA', '.']
    # Push with Commit SHA as Tag
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/http-response-emulator:$COMMIT_SHA']
    # Also add the latest tag
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/http-response-emulator:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/http-response-emulator:latest' ]